development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:1e8c773cd3702abfffafc157fe413777@spinyfin.redistogo.com:10757/
  #url: redis://localhost:6379/1
